Creature.destroy_all


Creature.create({name: "Princess Leia", description: "One of the most badass ladies in the Rebel Alliance.", image: "https://img.huffingtonpost.com/asset/586617791900002a000e22a5.jpeg?cache=p6yaxzb2rt&ops=scalefit_720_noupscale"})
Creature.create({name: "Luke Skywalker", description: "Tatooine farmboy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known.", image: "http://outerrimnews.com/wp-content/uploads/2017/05/luke-skywalker.jpg"})
Creature.create({name: "Hans Solo", description: "Smuggler. Scoundrel. Hero. Han Solo, captain of the Millennium Falcon, was one of the great leaders of the Rebel Alliance.", image: "https://lumiere-a.akamaihd.net/v1/images/Han-Solo_1d08eb2e.jpeg?region=0%2C1%2C1600%2C900&width=768"})
Creature.create({name: "Chewbacca", description: "A legendary Wookiee warrior and Han Solo's co-pilot aboard the Millennium Falcon, Chewbacca was part of a core group of Rebels who restored freedom to the galaxy.", image: "https://i0.wp.com/media2.slashfilm.com/slashfilm/wp/wp-content/images/empirestrikesback-chewbacca-tool.jpg"})
Creature.create({name: "Obi-Wan Kenobi", description: "A legendary Jedi Master, Obi-Wan Kenobi was a noble man and gifted in the ways of the Force. He trained Anakin Skywalker, served as a general in the Republic Army during the Clone Wars, and guided Luke Skywalker as a mentor.", image: "https://lumiere-a.akamaihd.net/v1/images/Obi-Wan-Kenobi_6d775533.jpeg?region=0%2C0%2C1536%2C864&width=768"})
Creature.create({name: "Darth Vader", description: "Once a heroic Jedi Knight, Darth Vader was seduced by the dark side of the Force, became a Sith Lord, and led the Empire's eradication of the Jedi Order.", image: "https://lumiere-a.akamaihd.net/v1/images/Darth-Vader_6bda9114.jpeg?region=0%2C23%2C1400%2C785&width=768"})
Creature.create({name: "Yoda", description: "Yoda was a legendary Jedi Master and stronger than most in his connection with the Force. Small in size but wise and powerful, he trained Jedi for over 800 years, playing integral roles in the Clone Wars, the instruction of Luke Skywalker, and unlocking the path to immortality.", image: "http://2.bp.blogspot.com/-7ijHiaiZmHg/VnK66LaABkI/AAAAAAAATWg/xQsF7zHeTsI/w1200-h630-p-k-no-nu/Yoda.jpg"})